#include "src/game/envfx_snow.h"

const GeoLayout wf_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_bg_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_bridge_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_ccm_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, wf_dl_ccm_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, wf_dl_ccm_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_garden_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, wf_dl_garden_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_greens_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_mirror_1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_rails_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_slide_secret_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, wf_dl_stairs_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_stairs_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_ttm_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_water_slide_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_dl_welt_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout wf_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 60000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, wf_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
